---
# basic
is_dev_environment: False
system_user: vagrant
system_home: "/home/{{ system_user }}"

# dotfiles setup
dotfiles_dest: "/home/{{ system_user }}/dotfiles"
dotfiles_github_repo: "mjs2600/dot_files"
dotfiles_setup_script: "{{ dotfiles_dest }}/dots.py"
