---

- name: install silver searcher
  apt: name=silversearcher-ag state=present update_cache=yes
  sudo: true
  when: is_dev_environment

- name: install ctags
  apt: name=ctags state=present
  sudo: true
  when: is_dev_environment

- name: clone dot files repository
  git: repo=git://github.com/{{ dotfiles_github_repo }}.git dest={{ dotfiles_dest }} update=yes
  sudo: true
  when: is_dev_environment

- name: run dot file setup script
  command: /usr/bin/python {{ dotfiles_setup_script }} {{ dotfiles_dest }} {{ system_home }}
  sudo: true
  when: is_dev_environment
