#:>>> INSTALL Python Dev Tools

- name: install ruby-dev
  apt: name=ruby-dev state=present
  sudo: True

- name: install bundler
  command: /usr/bin/gem install --no-user-install bundler
  # for reasons unknow the below passes successfully but does
  # not install bundle into any place I can currently identify.
  # look into more and fix.
  # gem: name=bundler state=present user_install=no
  sudo: True
