#:>>> INSTALL Node Dev Tools

- name: install node package manager (npm)
  apt: name=npm state=present update_cache=yes
  sudo: True

- name: gulp it up
  npm: name=gulp state=present global=yes

- name: symlink nodejs to node
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link
