---

- name: add tmate repository
  apt_repository: state=present repo='ppa:nviennot/tmate'
  sudo: true
  when: is_dev_environment

- name: install tmate
  apt: name=tmate state=present update_cache=yes
  sudo: true
  when: is_dev_environment

- name: ssh-keygen
  command: ssh-keygen -t rsa -f "{{ tmate_key_file }}" -N ''
  sudo_user: "{{ system_user }}"
  args:
    creates: "{{ tmate_key_file}}"
