---

#:>>> MAKE AND CONFIGURE DATABASE
- name: create database
  postgresql_db: name={{ dbname }} encoding='UTF-8'
  sudo_user: postgres

- name: create database user
  postgresql_user: name={{ dbname }} db={{ dbname }} role_attr_flags=SUPERUSER password={{ dbpasswd }}
  sudo_user: postgres

- name: ensure postgresql hstore extension is created
  sudo: true
  sudo_user: postgres
  shell: "psql {{ dbname }} -c 'CREATE EXTENSION hstore;'"
  register: psql_result
  failed_when: >
    psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
  changed_when: "psql_result.rc == 0"
